// import localFont from "next/font/local";
import Link from "next/link";
import Image from "next/image";
import Menu from "../../components/Menu";
// import {Navbar} from "@/components/Navbar";

export const metadata = {
  title: "Healthcare",
  description: "Generated by create next app",
};

export default function Dashboard({ children }) {
  return (
    <div
      className="h-screen flex"
      // style={{ display: "flex", height: "100vh", color: "black" }}
    >
      {/*left section */}
      <div className="w-[14%] md:w-[8%] lg:w-[16%] xl:w-[14%] bg-white p-4">
        <Link
          href="/"
          className="flex items-center justify-center lg:justify-start gap-2"
        >
          <Image src="/assets/logo.png" alt="logo" width={40} height={40} />
          <span className="hidden lg:block">Healthcare</span>{" "}
          {/* replace with web app name and logo*/}
        </Link>
       <Menu />
      </div>
      {/* right section*/}
      <div className="w-[86%] md:w-[92%] lg:w-[84%] xl:w-[86%] bg-blue-50 bg-[#F7F8FA] overflow-scroll">
        {/* <Navbar /> */}
        {children}
      </div>
    </div>
  );
}

